### ISSUE TITLE
Error on integer change weather.getWeatherForecastForDays(4, function(err, obj){

### ISSUE THREAD

**Issue by NMonst4** [CICCIOSGAMINO/openweather-apis#17]
When ich change the integer for day to 4 I get an error like this.

Code:
```javascript
weather.getWeatherForecastForDays(4, function(err, obj){
    console.log(err);
    console.log(obj);
});
```

Error:
```javascript
{ error: 
   SyntaxError: Unexpected number in JSON at position 1
       at Object.parse (native)
       at IncomingMessage.<anonymous> (###APPPATH###/node_modules/openweather-apis/index.js:185:27)
       at emitOne (events.js:96:13)
       at IncomingMessage.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:172:18)
       at IncomingMessage.Readable.push (_stream_readable.js:130:10)
       at HTTPParser.parserOnBody (_http_common.js:129:22)
       at Socket.socketOnData (_http_client.js:361:20)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7) }
```

**Comment by CICCIOSGAMINO** [comment]
You can have a Forecast on free version ....

**Comment by NMonst4** [comment]
The forecast is working but the most requests returns an error but sometimes it get datas from api. strange but ok for my project
